// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Passion_of_code.Models;

#nullable disable

namespace Passion_of_code.Migrations
{
    [DbContext(typeof(PassionOfCodeContext))]
    partial class PassionOfCodeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Passion_of_code.Models.Task", b =>
                {
                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.Property<int?>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Approach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Paradigm")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Part1_solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Part1_solved")
                        .HasColumnType("int");

                    b.Property<string>("Part2_solution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Part2_solved")
                        .HasColumnType("int");

                    b.HasKey("Year", "Day", "Username");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Passion_of_code.Models.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Eail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Passwd_hash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
